### ISSUE TITLE
this example not work for me.

### ISSUE THREAD

**Issue by sevketk** [dotnet/dotnet-api-docs.tr-tr#1]
I get error ;
Severity Level Code Description Project File Line Conceal Status Error CS0136 cannot be expressed in this scope because a local or parameter called 'sender' is used to define a locale or parameter in a closing local scope of this name code loader C: \ Users \ gamedeveloper \ source \ repos \ code installer \ code loader \ 
and 
Severity Rating Code Description Project File Trace Concealment Status
Error CS0136 A local or parameter called 'e' 'cannot be expressed in this scope because this name is used to define a locale or parameter in a closing local context code loader C: \ Users \ gamedeveloper \ source \ repos \ code loader \ code loader \ Form1.cs 26 Effective

---
#### Belge Ayrıntıları

⚠ *Bu bölümü düzenlemeyin. docs.microsoft.com ➟ GitHub sorunu bağlantısı için gereklidir.*

* ID: 5b9c1c5f-8228-9997-cd28-1224c573dfc5
* Version Independent ID: b8940d78-ca3d-0f8d-475c-ed9dd769eb00
* Content: [Process.OutputDataReceived Event (System.Diagnostics)](https://docs.microsoft.com/tr-tr/dotnet/api/system.diagnostics.process.outputdatareceived?view=netframework-4.8#feedback)
* Content Source: [xml/System.Diagnostics/Process.xml](https://github.com/dotnet/dotnet-api-docs.tr-tr/blob/live/xml/System.Diagnostics/Process.xml)
* Product: **dotnet-api**
* Technology: **system.diagnostics**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by CeciAc** [comment]
Hello, @sevketk 

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team
